version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: kfind-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: kfind-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
